apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::378102649368:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1A3NRZ5KRQNLI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::378102649368:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-16T14:43:49Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-16T14:43:49Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-01-16T18:20:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "35534"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e25df5db-4169-4433-aecb-a974e68779fd
